#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PinView.Droid.Resource", IsApplication=false)]

namespace PinView.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public static int accentColor = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int accentHeight = 2130771977;
			
			// aapt resource value: 0x7f010005
			public static int borderColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int digitBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int digitCount = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int digitHeight = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int digitSpacing = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int digitWidth = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public static int onPinFinished = 2130771978;
			
			// aapt resource value: 0x7f010007
			public static int textColor = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int textSize = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PinView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 8
			public static int PinView_accentColor = 8;
			
			// aapt resource value: 9
			public static int PinView_accentHeight = 9;
			
			// aapt resource value: 5
			public static int PinView_borderColor = 5;
			
			// aapt resource value: 4
			public static int PinView_digitBackgroundColor = 4;
			
			// aapt resource value: 0
			public static int PinView_digitCount = 0;
			
			// aapt resource value: 2
			public static int PinView_digitHeight = 2;
			
			// aapt resource value: 3
			public static int PinView_digitSpacing = 3;
			
			// aapt resource value: 1
			public static int PinView_digitWidth = 1;
			
			// aapt resource value: 10
			public static int PinView_onPinFinished = 10;
			
			// aapt resource value: 7
			public static int PinView_textColor = 7;
			
			// aapt resource value: 6
			public static int PinView_textSize = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
